# -*- coding: utf-8 -*-
"""File Dependencies

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xpLp08gwBQqmfW4kPEc77Pr8YOi2cxx
"""

import sys 
import matplotlib.pyplot as plt
import numpy as mp
from collections import defaultdict

"""# Section 1: Importing from the github repository."""

!git clone https://github.com/FamousStephens/COP5610-Term-Project.git

file_source = "COP5610-Term-Project/out.dot"
dependency_file = open(file_source, "r")

"""# Section 2: Creating the dictionary

To calculate the frequency of file dependency occurances, a dictionary will be used. The key value is the hash of a file, the value is the frequency of the hash.
"""

i = 0 
leng = 0
key = ['File'] # key for file and number of dependencies
d = defaultdict(list) #creating empty dictionary 

with open(file_source,"r") as dep_file:
  lines = dep_file.readlines()
  for line in lines:
      if line.find('{') != -1 or line.find('digraph') != -1 or line.find('}') != -1:
        continue
      elif line.find('[') != -1 or line.find('->') != -1 or line.find(']') != -1:
        continue
      else: # this will store the dependency files in a dictionary list
        d[i].append(line.strip('\n')) # removing newline from file entry
        i+=1

# go through again and create and compare files with how many times that they occur in the file to get the dependency count
print(d)